export const projectsData = [
    {
        id: 'jeevika',
        title: 'Jeevika - Healthcare App',
        description: "A complete healthcare platform with features Appointment management, telemedicine, medication manager, health records tracking, emergency services locator, and health education",
        technologies: ['Flutter', 'Firebase', "Material Design"],
        category: 'android',
        image: '/images/projects/jeevika.png',
        github_link: 'https://github.com/codewithdinesh/jeevika',
        link: 'https://jeevika-blush.vercel.app/',
    },
    {
        id: 'legalsathi',
        title: 'LegalSathi',
        description: 'AI-driven legal awareness platform featuring a chatbot with multi-language support for simplified legal document understanding.',
        technologies: ['Next.js', 'Tailwind', 'AI'],
        category: 'web',
        image: '/images/projects/legalsathi.png',
        github_link: 'https://github.com/codewithdinesh/SIH_2023/',
        link: 'https://sih-2023-gilt.vercel.app/',
    },
    {
        id: 'drustii',
        title: 'Drustii - Video Social Media Application',
        description: 'A YouTube-like video streaming platform with features such as user authentication, search, recommendation, video uploads, thumbnail generation, and OTP verification.',
        technologies: ['Android', 'AWS', 'Node.js'],
        category: 'android',
        image: '/images/projects/drustii.jpg',
        github_link: 'https://github.com/codewithdinesh/drusti-app',
        link: '',
    },
    {
        id: 'elogbook',
        title: 'Elogbook ',
        description: 'A web application for production logging with data visualizations, analytics which enhance decision-making efficiency and performance.',
        technologies: ['Next.js', 'Chart.js', 'Google Firebase'],
        category: 'web',
        image: '/images/projects/elogbook.png',
        github_link: 'https://github.com/codewithdinesh/elogbook',
        link: 'https://elogbook-kappa.vercel.app/',
    },
    {
        id: 'spaceventures',
        title: 'SpaceVentures',
        description: 'A platform for space tourism designed during a hackathon, featuring NASA datasets and interactive visualizations.',
        technologies: ['Next.js', 'Three.js', 'Tailwind'],
        category: 'web',
        image: '/images/projects/space_venture.gif',
        github_link: 'https://github.com/codewithdinesh/space-ventures',
        link: 'https://dyson-sphere.vercel.app/',
    },
    {
        id: 'agro-culture',
        title: 'Agro-Culture: Farmer Portal',
        description: 'A digital platform connecting farmers and buyers directly to facilitate the sale of agricultural products.',
        technologies: ['PHP', 'MySQL'],
        category: 'web',
        image: '/images/projects/agro_culture.png',
        github_link: 'https://github.com/codewithdinesh/agro-culture',
        link: '',
    },
    {
        id: 'youtube-brief',
        title: 'YouTube Brief',
        description: 'A tool for summarizing YouTube videos into text with support for multiple languages.',
        technologies: ['Python', 'API'],
        category: 'data science',
        image: '/images/projects/youtube-brief.jpg',
        github_link: 'https://github.com/codewithdinesh/YTSummarize',
        link: '',
    },
    {
        id: 'chatting-app',
        title: 'Chatting App',
        description: 'A real-time chat application with Firebase for seamless and instant communication.',
        technologies: ['Next.js', 'Firebase'],
        category: 'web',
        image: '/images/projects/chat_app.png',
        github_link: 'https://github.com/codewithdinesh/whatsapp-2',
        link: 'https://my-whats-app.vercel.app/',
    },
    {
        id: 'brief-web',
        title: 'Brief Web - AI Website Summarizer',
        description: 'An AI-powered tool to summarize websites and articles, enhancing comprehension for users.',
        technologies: ['Next.js', 'GPT'],
        category: 'machine learning',
        image: '/images/projects/brief_web.png',
        github_link: 'https://github.com/codewithdinesh/brief-web',
        link: 'https://brief-web.vercel.app/',
    },
    {
        id: 'doit',
        title: 'Doit - Task Management App',
        description: 'A task management application that enables users to create, manage, and track tasks efficiently.',
        technologies: ['Android', 'Google Firebase', 'Material Design'],
        category: 'android',
        image: '/images/projects/do_it.jpg',
        github_link: 'https://github.com/codewithdinesh/do-its',
        link: '',
    },
    {
        id: 'exam-result-management-system',
        title: 'Exam Result Management System',
        description: 'A web-based system for managing exam results using Node.js, MongoDB, and EJS templating.',
        technologies: ['Node.js', 'MongoDB', 'EJS'],
        category: 'web',
        image: '/images/projects/result-management-system.png',
        github_link: 'https://github.com/codewithdinesh/result-mangement-system',
        link: 'https://result-mangement-system.onrender.com/',
    },
    {
        id: 'qr-attendance-system',
        title: 'QR Attendance System',
        description: 'An Android app for managing attendance through QR code scanning and real-time data synchronization.',
        technologies: ['Android', 'Firebase'],
        category: 'android',
        image: '/images/projects/qr_attendance_system.png',
        github_link: 'https://github.com/codewithdinesh/qr-attendance-android',
        link: '',
    }
];
