export const projectsData = [
    {
        id: "location-intelligence",
        title: "Business Expansion System using Location Intelligence",
        description:
            "AI-powered geospatial platform to help food and restaurant businesses make data-driven location decisions by integrating satellite data, business trends, infrastructure, and economic indicators.",
        technologies: ["QGIS", "Geoviz", "Machine Learning", "DBSCAN"],
        category: ["data science", "Artificial Intelligence"],
        image: "/images/projects/location_intelligence.png",
        github_link: "",
        link: "",
    },

    {
        id: "autofill",
        title: "Autofill - Smart Job Application Assistant",
        description:
            "AI-powered Chrome extension designed to auto-fill job application forms intelligently, extracting and matching resume data to form fields for faster application submission.",
        technologies: ["React.js", "WXT", "Chrome Extension API", "AI"],
        category: ["web", "Artificial Intelligence", "tools"],
        image: "/images/projects/autofill.png",
        github_link: "https://github.com/codewithdinesh/autofill",
        link: "",
    },
    {
        id: "jeevika",
        title: "Jeevika - Healthcare App",
        description:
            "A complete healthcare platform with features Appointment management, telemedicine, medication manager, health records tracking, emergency services locator, and health education",
        technologies: ["Flutter", "Firebase", "Material Design"],
        category: ["android", "web"],
        image: "/images/projects/jeevika.png",
        github_link: "https://github.com/codewithdinesh/jeevika",
        link: "https://jeevika-blush.vercel.app/",
    },
    {
        id: "legalsathi",
        title: "LegalSathi",
        description:
            "AI-driven legal awareness platform featuring a chatbot with multi-language support for simplified legal document understanding.",
        technologies: ["Next.js", "Tailwind", "AI"],
        category: ["web"],
        image: "/images/projects/legalsathi.png",
        github_link: "https://github.com/codewithdinesh/SIH_2023/",
        link: "https://sih-2023-gilt.vercel.app/",
    },
    {
        id: "drustii",
        title: "Drustii - Video Social Media Application",
        description:
            "A YouTube-like video streaming platform with features such as user authentication, search, recommendation, video uploads, thumbnail generation, and OTP verification.",
        technologies: ["Android", "AWS", "Node.js"],
        category: ["android"],
        image: "/images/projects/drustii.jpg",
        github_link: "https://github.com/codewithdinesh/drusti-app",
        link: "",
    },
    {
        id: "elogbook",
        title: "Elogbook ",
        description:
            "A web application for production logging with data visualizations, analytics which enhance decision-making efficiency and performance.",
        technologies: ["Next.js", "Chart.js", "Google Firebase"],
        category: ["web"],
        image: "/images/projects/elogbook.png",
        github_link: "https://github.com/codewithdinesh/elogbook",
        link: "https://elogbook-kappa.vercel.app/",
    },
    {
        id: "spaceventures",
        title: "SpaceVentures",
        description:
            "A platform for space tourism designed during a hackathon, featuring NASA datasets and interactive visualizations.",
        technologies: ["Next.js", "Three.js", "Tailwind"],
        category: ["web"],
        image: "/images/projects/space_venture.gif",
        github_link: "https://github.com/codewithdinesh/space-ventures",
        link: "https://dyson-sphere.vercel.app/",
    },
    {
        id: "agro-culture",
        title: "Agro-Culture: Farmer Portal",
        description:
            "A digital platform connecting farmers and buyers directly to facilitate the sale of agricultural products.",
        technologies: ["PHP", "MySQL"],
        category: ["web"],
        image: "/images/projects/agro_culture.png",
        github_link: "https://github.com/codewithdinesh/agro-culture",
        link: "",
    },
    {
        id: "youtube-brief",
        title: "YouTube Brief",
        description:
            "A tool for summarizing YouTube videos into text with support for multiple languages.",
        technologies: ["Python", "API"],
        category: ["data science"],
        image: "/images/projects/youtube-brief.jpg",
        github_link: "https://github.com/codewithdinesh/YTSummarize",
        link: "",
    },
    {
        id: "chatting-app",
        title: "Chatting App",
        description:
            "A real-time chat application with Firebase for seamless and instant communication.",
        technologies: ["Next.js", "Firebase"],
        category: ["web"],
        image: "/images/projects/chat_app.png",
        github_link: "https://github.com/codewithdinesh/whatsapp-2",
        link: "https://my-whats-app.vercel.app/",
    },
    {
        id: "brief-web",
        title: "Brief Web - AI Website Summarizer",
        description:
            "An AI-powered tool to summarize websites and articles, enhancing comprehension for users.",
        technologies: ["Next.js", "GPT"],
        category: ["Artificial Intelligence", "web"],
        image: "/images/projects/brief_web.png",
        github_link: "https://github.com/codewithdinesh/brief-web",
        link: "https://brief-web.vercel.app/",
    },
    {
        id: "doit",
        title: "Doit - Task Management App",
        description:
            "A task management application that enables users to create, manage, and track tasks efficiently.",
        technologies: ["Android", "Google Firebase", "Material Design"],
        category: ["android"],
        image: "/images/projects/do_it.jpg",
        github_link: "https://github.com/codewithdinesh/do-its",
        link: "",
    },
    {
        id: "exam-result-management-system",
        title: "Exam Result Management System",
        description:
            "A web-based system for managing exam results using Node.js, MongoDB, and EJS templating.",
        technologies: ["Node.js", "MongoDB", "EJS"],
        category: ["web"],
        image: "/images/projects/result-management-system.png",
        github_link: "https://github.com/codewithdinesh/result-mangement-system",
        link: "https://result-mangement-system.onrender.com/",
    },
    {
        id: "qr-attendance-system",
        title: "QR Attendance System",
        description:
            "An Android app for managing attendance through QR code scanning and real-time data synchronization.",
        technologies: ["Android", "Firebase"],
        category: ["android"],
        image: "/images/projects/qr_attendance_system.png",
        github_link: "https://github.com/codewithdinesh/qr-attendance-android",
        link: "",
    },
    {
        id: "smartslot",
        title: "SmartSlot",
        description:
            "An innovative AI-driven system designed for efficient delivery slot management, optimizing delivery operations and enhancing customer satisfaction.",
        technologies: ["Next.js", "AI", "Tailwind"],
        category: ["web", "Artificial Intelligence"],
        image: "/images/projects/smartslot.png",
        github_link: "https://github.com/codewithdinesh/SIH_1761_CodexGigas",
        link: "https://smartslot.vercel.app/",
    },
    {
        id: "tailoring-website",
        title: "Tailoring Service Website",
        description:
            "An interactive platform for accessing tailoring services online, providing a seamless interface between customers and tailors.",
        technologies: ["MERN", "MongoDB", "Express", "React", "Node.js"],
        category: ["web"],
        image: "/images/projects/tailoring.png",
        github_link: "https://github.com/codewithdinesh/tailoring-website",
        link: "",
    },
    {
        id: "dkfilms",
        title: "DKFilms - Video OTT Platform UI",
        description:
            "A modern video OTT platform UI developed with Next.js and Material Design, featuring a sleek interface for content discovery and streaming.",
        technologies: ["Next.js", "Material Design"],
        category: ["web"],
        image: "/images/projects/dkfilms.png",
        github_link: "https://github.com/codewithdinesh/dkflims",
        link: "https://dkflims.vercel.app/",
    },
    {
        id: "rapidvidya",
        title: "Rapid Vidya",
        description:
            "AI-powered last-moment study tool that helps students quickly grasp essential concepts before exams, utilizing OpenAI API for intelligent content generation.",
        technologies: ["Next.js", "OpenAI API", "Tailwind"],
        category: ["web", "Artificial Intelligence", "education"],
        image: "/images/projects/rapidvidya.png",
        github_link: "https://github.com/codewithdinesh/rapidvidya",
        link: "https://rapidvidya.vercel.app",
    },
    {
        id: "inbox-harbor",
        title: "InboxHarbor",
        description:
            "A specialized tool that extracts email addresses from websites, streamlining outreach and contact management processes.",
        technologies: ["Next.js", "Tailwind"],
        category: ["web", "tools"],
        image: "/images/projects/inbox_harbor.png",
        github_link: "https://github.com/codewithdinesh/InboxHarbor",
        link: "https://inbox-harbor.vercel.app/",
    },
    {
        id: "news-adda",
        title: "News Adda",
        description:
            "A responsive news website built with React.js that provides the latest articles with a user-friendly interface and efficient content categorization.",
        technologies: ["React.js", "News API"],
        category: ["web"],
        image: "/images/projects/news_adda.png",
        github_link: "https://github.com/codewithdinesh/news-adda",
        link: "",
    },
    {
        id: "bidding-system",
        title: "Realtime Bidding System",
        description:
            "A Next.js-based application for managing bids where users can view ongoing and expired bids, and creators can create new bids with real-time updates.",
        technologies: ["Next.js", "Firebase", "Realtime Database"],
        category: ["web"],
        image: "/images/projects/bidding_system.png",
        github_link: "https://github.com/codewithdinesh/bidding-system",
        link: "https://bidding-system-red.vercel.app/",
    },
    {
        id: "finwiz",
        title: "FinWiz",
        description:
            "AI-powered financial advice platform that provides personalized guidance based on financial parameters like savings, assets, liabilities, and goals.",
        technologies: ["React.js", "Node.js", "GPT"],
        category: ["web", "Artificial Intelligence", "finance"],
        image: "/images/projects/finwiz.png",
        github_link: "https://github.com/codewithdinesh/finwiz",
        link: "",
    },
    {
        id: "movieverse",
        title: "MovieVerse",
        description:
            "A simple yet elegant Movie Catalog web application built with Next.js and Tailwind CSS for exploring and discovering movies.",
        technologies: ["Next.js", "Tailwind CSS", "Movie API"],
        category: ["web"],
        image: "/images/projects/movieverse.png",
        github_link: "https://github.com/codewithdinesh/movieVerse",
        link: "https://movie-verse-olive.vercel.app/",
    },
    {
        id: "ai-image-generator",
        title: "AI Image Generator",
        description:
            "Web application that generates images through AI using advanced APIs, allowing users to create unique visuals from text descriptions.",
        technologies: ["Next.js", "AI API"],
        category: ["web", "Artificial Intelligence"],
        image: "/images/projects/ai_image_gen.png",
        github_link: "https://github.com/codewithdinesh/ai-image-generator",
        link: "https://ai-img-gen-dinesh.vercel.app/",
    },
    {
        id: "weather-forecast-app",
        title: "Weather Forecast App",
        description:
            "Weather forecast application built with HTML, CSS, and JavaScript that provides real-time weather information using a weather API.",
        technologies: ["HTML", "CSS", "JavaScript", "Weather API"],
        category: ["web"],
        image: "/images/projects/weather_app.png",
        github_link: "https://github.com/codewithdinesh/weather-app",
        link: "",
    },
    {
        id: "placed",
        title: "Placed - Training and Placement Portal",
        description:
            "A comprehensive mobile solution for streamlining the training and placement process, allowing students to manage profiles, apply for placements, and interact with recruiters.",
        technologies: ["Node.js", "Android", "Material Design"],
        category: ["android", "web"],
        image: "/images/projects/placed.png",
        github_link: "https://github.com/codewithdinesh/placed",
        link: "",
    },
    {
        id: "pure-play",
        title: "PurePlay - OTT Platform",
        description:
            "A video streaming OTT platform built with Flutter, featuring different video playing options and user preference settings.",
        technologies: ["Flutter", "Video Streaming"],
        category: ["android"],
        image: "/images/projects/pureplay.png",
        github_link: "https://github.com/codewithdinesh/PurePlay",
        link: "",
    },
    {
        id: "marksheet-analyzer",
        title: "Marksheet Analyzer",
        description:
            "Automated student performance analysis tool using PDF data extraction and Pandas for comprehensive educational data analytics.",
        technologies: ["Python", "Pandas", "Data Analysis"],
        category: ["data science", "education"],
        image: "/images/projects/marksheet_analyzer.png",
        github_link: "https://github.com/codewithdinesh/marksheet-analysis",
        link: "",
    },
    {
        id: "career-recommendation",
        title: "Career Recommendation App",
        description:
            "A web application that helps users discover suitable career options based on their personality traits through a series of targeted questions.",
        technologies: ["Streamlit", "Python", "ML"],
        category: ["web", "Artificial Intelligence"],
        image: "/images/projects/career_recommendation.png",
        github_link: "https://github.com/codewithdinesh/career-recommendation",
        link: "https://career-recommendation.streamlit.app/",
    },
];
